language: objective-c
xcode_workspace: KeyPathBindings.xcworkspace
xcode_scheme: KeyPathBindings
os: osx
osx_image: xcode9.3beta
script: xcodebuild clean build -sdk iphonesimulator -workspace KeyPathBindings.xcworkspace -scheme KeyPathBindings CODE_SIGNING_REQUIRED=NO

